import QtQuick

// Generated by tools/generate-clock-hole.py from assets/cat-hat.png alpha.
QtObject {
    readonly property real sourceWidth: 894
    readonly property real sourceHeight: 954
    readonly property real holeCx: 427.500
    readonly property real holeCy: 619.000
    readonly property real faceRadius: 333.000
}
