#!/usr/bin/env python3
import math
import statistics
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSET_DIR = ROOT / "assets"
SOURCE = ASSET_DIR / "cat-hat.png"
BAKED = ASSET_DIR / "cat-hat-clock.png"
GEOMETRY_QML = ROOT / "ClockHatGeometry.qml"

ALPHA_THRESHOLD = 128
MIN_WALL_RUN = 20
FACE_Y_MIN = 330
FACE_Y_MAX = 909
REFERENCE_X = 430
GLASS_COLOR = "#ffffff"
# Slight visual oversize so the circular clock face fills the furry opening better.
FACE_RADIUS_GROW = 45


def image_size(path):
    out = subprocess.check_output(
        ["identify", "-format", "%w %h", str(path)],
        text=True,
    )
    return tuple(map(int, out.split()))


def alpha_bytes(path):
    return subprocess.check_output(
        ["magick", str(path), "-alpha", "extract", "-depth", "8", "gray:-"]
    )


def opaque_runs(row, threshold):
    runs = []
    start = None
    prev = None
    for x, value in enumerate(row):
        if value > threshold:
            if start is None:
                start = prev = x
            elif x == prev + 1:
                prev = x
            else:
                if prev - start + 1 >= MIN_WALL_RUN:
                    runs.append((start, prev))
                start = prev = x
    if start is not None and prev - start + 1 >= MIN_WALL_RUN:
        runs.append((start, prev))
    return runs


def face_intervals(width, alpha):
    intervals = {}
    for y in range(FACE_Y_MIN, FACE_Y_MAX + 1):
        row = alpha[y * width : (y + 1) * width]
        runs = opaque_runs(row, ALPHA_THRESHOLD)
        gaps = []
        for (_, left_end), (right_start, _) in zip(runs, runs[1:]):
            left = left_end + 1
            right = right_start - 1
            if left <= REFERENCE_X <= right:
                gaps.append((left, right))
        if gaps:
            intervals[y] = max(gaps, key=lambda span: span[1] - span[0])
    return intervals


def circle_fits(intervals, cx, cy, radius):
    low = math.floor(cy - radius)
    high = math.ceil(cy + radius)
    for y in range(low, high + 1):
        if y not in intervals:
            return False
        dy = y - cy
        x_span_sq = radius * radius - dy * dy
        if x_span_sq < 0:
            continue
        x_span = math.sqrt(x_span_sq)
        left, right = intervals[y]
        if cx - x_span < left or cx + x_span > right:
            return False
    return True


def max_radius_at(intervals, cx, cy):
    low = 0.0
    high = 360.0
    for _ in range(32):
        mid = (low + high) / 2
        if circle_fits(intervals, cx, cy, mid):
            low = mid
        else:
            high = mid
    return low


def solve_circle(intervals):
    wide_midpoints = [
        (left + right) / 2
        for left, right in intervals.values()
        if right - left + 1 >= 500
    ]
    cx = statistics.median(wide_midpoints)

    best_y = FACE_Y_MIN
    best_r = 0.0
    for half_px in range(FACE_Y_MIN * 2, FACE_Y_MAX * 2 + 1):
        cy = half_px / 2
        radius = max_radius_at(intervals, cx, cy)
        if radius > best_r:
            best_y = cy
            best_r = radius

    return cx, best_y, math.floor(best_r)


def write_geometry(width, height, cx, cy, radius):
    GEOMETRY_QML.write_text(
        "\n".join(
            [
                "import QtQuick",
                "",
                "// Generated by tools/generate-clock-hole.py from assets/cat-hat.png alpha.",
                "QtObject {",
                f"    readonly property real sourceWidth: {width}",
                f"    readonly property real sourceHeight: {height}",
                f"    readonly property real holeCx: {cx:.3f}",
                f"    readonly property real holeCy: {cy:.3f}",
                f"    readonly property real faceRadius: {radius:.3f}",
                "}",
                "",
            ]
        )
    )


def bake_clock(width, height, cx, cy, radius):
    subprocess.check_call(
        [
            "magick",
            str(SOURCE),
            "(",
            "-size",
            f"{width}x{height}",
            "xc:none",
            "-fill",
            GLASS_COLOR,
            "-draw",
            f"ellipse {cx:.3f},{cy:.3f} {radius:.3f},{radius:.3f} 0,360",
            ")",
            "-compose",
            "DstOver",
            "-composite",
            str(BAKED),
        ]
    )


def main():
    width, height = image_size(SOURCE)
    alpha = alpha_bytes(SOURCE)
    intervals = face_intervals(width, alpha)
    if not intervals:
        raise SystemExit("no face intervals found")

    cx, cy, radius = solve_circle(intervals)
    radius += FACE_RADIUS_GROW
    write_geometry(width, height, cx, cy, radius)
    bake_clock(width, height, cx, cy, radius)

    widest_y, widest_span = max(
        intervals.items(),
        key=lambda item: item[1][1] - item[1][0],
    )
    print(f"hole axis x={cx:.3f}")
    print(f"widest row y={widest_y} span={widest_span[0]}..{widest_span[1]}")
    print(f"face circle cx={cx:.3f} cy={cy:.3f} r={radius:.3f}")
    print(f"wrote {GEOMETRY_QML}")
    print(f"wrote {BAKED}")


if __name__ == "__main__":
    main()
